package by.server.models.enums;

public enum RequestType {
    REGISTER,
    LOGIN,

    CALCULATE_PRODUCT_PRICE,
    UPDATE_USER_PRODUCT,
    DELETE_USER_PRODUCT,
    GET_USER_PRODUCTS,
    UPDATE_USER_ACCOUNT,
    DELETE_USER_ACCOUNT,
    CHANGE_PASSWORD,

    CHANGE_ROLE,
    GET_LOG_INFO,
    CHANGE_PRODUCT_DATA,
    DELETE_PRODUCT,
    BAN_USER,
    UNBAN_USER,
    DELETE_ACCOUNT,
    GET_USER_INFO,

    GET_ALL_PRODUCTS,
    GET_ALL_ACCOUNTS,
    GET_ALL_BANS,

    CREATE_REPORT_MARGINALITY,
    CREATE_REPORT_EXPENSES_PRODUCT,
    GET_PRICE_HISTORY
}
